### ISSUE TITLE
Filtering triples

### ISSUE THREAD

**Issue by reni99** [csarven/transparency-linked-data#1]
If you run the file tarql.mappingCPI2012.sparql from the branch CPI2012 with tarql you will see that it will create all triples, including the ones where the score from the surveys are equal to 0.
So the output is as follows (example for African Development Bank Governance Ratings, Limited to 1 set of triples):
...
<http://transparency.270a.info/dataset/corruption-perceptions-index/2012/sources/african-development-bank-country-policy-and-institutional-assessment-governance-ratings/2012/DK>
      rdf:type      qb:Observation ;
      rdfs:label    "Corruption Perception Index 2012 for Denmark from African Development Bank Governance Ratings in 2012" ;
      dcterms:source  <http://cpia.afdb.org/> ;
      qb:dataSet    "http://transparency.270a.info/dataset/corruption-perceptions-index/2012/sources" ;
      sdmx-attribute:adjustment
                    <http://transparency.270a.info/classification/attribute/matching-percentiles> ;
      sdmx-dimension:refArea
                    <http://transparency.270a.info/classification/country/DK> ;
      sdmx-dimension:refPeriod
                    <http://reference.data.gov.uk/id/year/2012> ;
      property:score  "0"^^xsd:decimal ;
      property:source  <http://transparency.270a.info/classification/source/african-development-bank-country-policy-and-institutional-assessment-governance-ratings/2012> .
...
You see that these triples should not be generated, since the property:score  is equal to "0"^^xsd:decimal ; --> e.g There was no survey for Denmark from African Development Bank.

I tried to exclude these triples with the following:
- MINUS{?observationAFDB property:score "0"^^xsd:decimal} //this didn't work
- FILTER(?scoreAFDB < 1) //this filtered everything e.g --> this filtered every triple, which was generated for Denmark (also triples where there were actually surveys)
- and OPTIONAL{} //this had no impact

Do you have a hint or idea how I can approach this? Thx

**Comment by csarven** [comment]
Either I did something wrong when I created the CSV or LibreOffice apparently didn't do what it was supposed to do i.e., saving the cell content as shown. The problem is that, the raw data actually contains a 0 value but it is set to as visually hidden in the Excel file. So, before filtering 0 out, you need to know whether to do that or not in the first place (unless you do, never mind). I suggest the following:

Check the CPI documentation to see whether they say anything about 0 values. And/or contact TI about "how to treat 0 values". You may also be able to compute the CPI score yourself (based on the values from the sources and the algorithm that's used for the calculation).

My interpretation is that, the visual version is what's intended i.e., they probably started out all cells with zeros and then added the values for what's available. Note that, 0 and undefined are not the same thing, so we have to be careful here. Here, undefined (what you see visually) is probably what's intended as opposed to the raw value (which is the 0). Double-check in any case!

Just to be clear on why the final output should not produce a triple set, if their score is unavailable. It doesn't make sense to create an observation with no measurement as `property:score` is a `qb:MeasureProperty`. No measure, no phenomenon observed. See also: http://www.w3.org/TR/vocab-data-cube/#ic-6

Try to save the original XLS as CSV and omit the 0s (the ones that you are sure that's not the intended 0 but that it is supposed to be undefined). Use that. Changing the 0s to null will still create the triple set, but without the triple with `property:score`.

As for controlling a _particular triple set_ (based on the existence of one its variables), I'm not sure if that's possible via SPARQL or tarql. You can try and see if sub-queries work - may be more complicated.

The last option is to leave it for post-mapping via a) command-line tools, or b) load it up in an RDF store, and then create a new `CONSTRUCT` leaving out the basic graph pattern that doesn't include a triple with property:score. Either use a local TDB for this, to load and export. Or, use Rasqal.

**Comment by reni99** [comment]
I solved the problem by using Jena Fuseki Server. First I loaded the existing triples into an RDF store and created two new `CONSTRUCT` to query for the needed results.
