### ISSUE TITLE
CPI generation method

### ISSUE THREAD

**Issue by reni99** [csarven/transparency-linked-data#3]
The CPI2012 is calculated by subtracting the mean of the data (13 sources) and dividing them by the standard deviation and then rescaled to have a mean 45 and standard deviation 20..

![image](https://cloud.githubusercontent.com/assets/6748633/4872103/293b7654-61d9-11e4-9937-163eb4a885db.png)

I searched for a term for this calculation on dbpedia, but could not find anything. Do you have a hint where I can possibly find a term for such a calculation?

**Comment by csarven** [comment]
If the calculation is an unique algorithm, create a new resource for it. Then provide a description for that resource e.g., label, description, and references to where more information about it can be found (e.g., URL to the TI doc)

**Comment by reni99** [comment]
How about the following?

@prefix skos: http://www.w3.org/2004/02/skos/core# .
@prefix rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns# .
@prefix rdfs: http://www.w3.org/2000/01/rdf-schema# .

<http://transparency.270a.info/classification/attribute/cpi-calculation-methology>
    skos:prefLabel "CPI Calculation Methology"@en ;
    rdf:type skos:Concept;
    skos:definition "This is the methology that Transparency International uses to calculate the CPI. the CPI is standardized by subtracting the mean of the sources and dividing by the standard deviation (z-scores) and the rescaled to have a mean 45 and standard deviation 20"@en ;
    rdfs:IsDefinedBy <http://files.transparency.org/content/download/534/2217/file/JRC_Statistical_Assessment_CPI2012_FINAL.pdf> ;
    skos:inScheme <http://transparency.270a.info/classification/attribute> ;
    skos:topConceptOf <http://transparency.270a.info/classification/attribute> .

**Comment by csarven** [comment]
Yes, that's along the lines of http://transparency.270a.info/classification/attribute/matching-percentiles but I would say that "cpi-calculation-methodology" is not specific enough. In fact, you could say that for any year.

"cpi-2012-methodology" would be more unique, but then it its subject to not being reusable in the future. CPI 2013 looks like it is using the same methodology, so that will work out okay, but it is hard to tell going forward. After all, TI did change their methodology over the years. In any case, under normal circumstances, you don't want to put a year in the URL.

Reading a little bit of their doc, perhaps something along the lines of "standardized-mean" might be okay.

Why not contact TI and ask them to clarify or help you come up with a term? See what they think of  "standardized-mean". I'll try to put you in contact with some individuals there.

s/IsDefinedBy/isDefinedBy

**Comment by reni99** [comment]
My attempts to get in contact with them were not successful. Got no reply from them. The closest description is here: http://files.transparency.org/content/download/534/2217/file/JRC_Statistical_Assessment_CPI2012_FINAL.pdf. But no well known terms are mentioned.
